import Link from "next/link";
import { AdminCard, AdminPageHeader, EmptyState, Pagination, StatusPill, tableClass, tdClass, thClass } from "@/components/admin/ui";
import { listCustomers, type PageInput } from "@/lib/admin/queries";
import { formatDate } from "@/lib/utils";

export default async function CustomersPage({ searchParams }: { searchParams: Promise<PageInput> }) {
  const data = await listCustomers(await searchParams);
  return <>
    <AdminPageHeader title="Customers" description="Customer contact, company and account records with booking and financial history." actions={<form className="flex gap-2"><input name="q" defaultValue={data.q} placeholder="Name, company or email" className="rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm" /><select name="status" defaultValue={data.status} className="rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm"><option value="">All types</option><option value="individual">Individual</option><option value="corporate">Corporate</option></select><button className="rounded-lg bg-white px-3 py-2 text-sm font-semibold text-black">Filter</button></form>} />
    <AdminCard className="overflow-hidden">{data.rows.length === 0 ? <EmptyState title="No customers found" /> : <div className="overflow-x-auto"><table className={tableClass}><thead><tr><th className={thClass}>Customer</th><th className={thClass}>Type / company</th><th className={thClass}>Phone</th><th className={thClass}>Location</th><th className={thClass}>Joined</th><th className={thClass}>Account</th><th className={thClass}></th></tr></thead><tbody>{data.rows.map(({ customer, email, isActive }) => <tr key={customer.id}><td className={tdClass}><strong>{customer.fullName}</strong><div className="mt-1 text-xs text-muted">{email}</div></td><td className={tdClass}>{customer.type}<div className="mt-1 text-xs text-muted">{customer.companyName || "—"}</div></td><td className={tdClass}>{customer.mobileNumber || "—"}<div className="mt-1 text-xs text-muted">WA {customer.whatsappNumber || "—"}</div></td><td className={tdClass}>{[customer.city, customer.country].filter(Boolean).join(", ") || "—"}</td><td className={tdClass}>{formatDate(customer.createdAt)}</td><td className={tdClass}><StatusPill value={isActive ? "active" : "inactive"} /></td><td className={tdClass}><Link href={`/admin/customers/${customer.id}`} className="text-xs font-semibold text-accent">Open</Link></td></tr>)}</tbody></table></div>}<Pagination page={data.page} pageSize={data.pageSize} total={data.total} pathname="/admin/customers" query={{ q: data.q, status: data.status }} /></AdminCard>
  </>;
}
