import { AdminCommandButton, DynamicAdminForm } from "@/components/admin/dynamic-form";
import { AdminCard, AdminPageHeader, StatusPill, tableClass, tdClass, thClass } from "@/components/admin/ui";
import { requireAdmin } from "@/lib/admin/authz";
import { hasPermission, STAFF_ROLES } from "@/lib/admin/permissions";
import { listStaff } from "@/lib/admin/queries";
import { formatDate } from "@/lib/utils";

export default async function StaffUsersPage() {
  const actor = await requireAdmin("users.read"); const rows = await listStaff(); const canManage = hasPermission(actor.role, "users.manage_roles");
  return <><AdminPageHeader title="Staff users" description="Invite-only staff access, role assignments, active status, MFA posture and immediate session revocation." />
    {canManage && <div className="mb-6"><DynamicAdminForm command="staff.invite" title="Invite a staff member" submitLabel="Create secure invitation" confirmMessage="Create a 48-hour one-time staff invitation?" fields={[{ name: "email", label: "Staff email", type: "email", required: true }, { name: "role", label: "Role", type: "select", required: true, options: STAFF_ROLES.map((role) => ({ value: role, label: role.replaceAll("_", " ") })) }]} /></div>}
    <AdminCard className="overflow-hidden"><div className="overflow-x-auto"><table className={tableClass}><thead><tr><th className={thClass}>Staff</th><th className={thClass}>Role</th><th className={thClass}>Account</th><th className={thClass}>MFA</th><th className={thClass}>Last login</th><th className={thClass}>Security actions</th></tr></thead><tbody>{rows.map((user) => <tr key={user.id}><td className={tdClass}><strong>{user.name}</strong><div className="text-xs text-muted">{user.email}</div></td><td className={tdClass}>{canManage && user.id !== actor.id ? <DynamicAdminForm command="staff.update" fixed={{ id: user.id, operation: "change_role" }} compact submitLabel="Change role" confirmMessage="Changing a role revokes all sessions. Continue?" fields={[{ name: "role", label: "Role", type: "select", required: true, defaultValue: user.role, options: STAFF_ROLES.map((role) => ({ value: role, label: role.replaceAll("_", " ") })) }]} /> : <StatusPill value={user.role} />}</td><td className={tdClass}><StatusPill value={user.isActive ? "active" : "inactive"} /><div className="mt-1 text-xs text-muted">Session version {user.sessionVersion}</div></td><td className={tdClass}><StatusPill value={user.mfaEnabled ? "enabled" : "not enabled"} /></td><td className={tdClass}>{formatDate(user.lastLoginAt)}</td><td className={tdClass}>{canManage && <div className="flex flex-wrap gap-2"><AdminCommandButton payload={{ action: "staff.update", id: user.id, operation: "revoke_sessions" }} confirmMessage="Sign this user out on all devices?">Revoke sessions</AdminCommandButton>{user.id !== actor.id && <AdminCommandButton payload={{ action: "staff.update", id: user.id, operation: user.isActive ? "deactivate" : "activate" }} tone={user.isActive ? "danger" : "default"} confirmMessage={`${user.isActive ? "Deactivate" : "Activate"} this staff account?`}>{user.isActive ? "Deactivate" : "Activate"}</AdminCommandButton>}{user.mfaEnabled && user.id !== actor.id && <AdminCommandButton payload={{ action: "staff.update", id: user.id, operation: "reset_mfa" }} tone="danger" confirmMessage="Reset MFA and revoke this user's sessions?">Reset MFA</AdminCommandButton>}</div>}</td></tr>)}</tbody></table></div></AdminCard>
  </>;
}
