"use client";

import { useState } from "react";
import { signOut } from "next-auth/react";
import { toast } from "sonner";
import { KeyRound, ShieldCheck } from "lucide-react";

export function MfaEnrollment({ enabled, verified, required }: { enabled: boolean; verified: boolean; required: boolean }) {
  const [secret, setSecret] = useState<string | null>(null); const [uri, setUri] = useState<string | null>(null); const [codes, setCodes] = useState<string[] | null>(null); const [pending, setPending] = useState(false);
  async function setup() { setPending(true); try { const res = await fetch("/api/auth/mfa/setup", { method: "POST" }); const body = await res.json(); if (!res.ok) throw new Error(body.error); setSecret(body.secret); setUri(body.provisioningUri); } catch (e) { toast.error(e instanceof Error ? e.message : "MFA setup failed"); } finally { setPending(false); } }
  async function enable(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); const code = new FormData(event.currentTarget).get("code"); try { const res = await fetch("/api/auth/mfa/enable", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ code }) }); const body = await res.json(); if (!res.ok) throw new Error(body.error); setCodes(body.recoveryCodes); toast.success("MFA enabled. Save your recovery codes."); } catch (e) { toast.error(e instanceof Error ? e.message : "Code verification failed"); } finally { setPending(false); } }
  return <section className={`rounded-2xl border p-5 ${required && (!enabled || !verified) ? "border-amber-400/30 bg-amber-400/[0.05]" : "border-white/8 bg-white/[0.025]"}`}><div className="flex items-start gap-3"><div className="rounded-xl bg-accent/15 p-2.5 text-accent"><ShieldCheck className="h-5 w-5" /></div><div><h2 className="font-semibold">Multi-factor authentication</h2><p className="mt-1 text-sm text-muted">{enabled ? verified ? "This session passed authenticator verification." : "MFA is enabled; sign in again with a code." : required ? "Your role requires MFA before other Admin features can be used." : "Add an authenticator for stronger account security."}</p></div></div>{!enabled && !secret && <button onClick={setup} disabled={pending} className="mt-5 rounded-xl bg-accent px-4 py-2.5 text-sm font-semibold text-white"><KeyRound className="mr-2 inline h-4 w-4" />Set up authenticator</button>}{secret && <div className="mt-5 rounded-xl border border-white/10 bg-black/20 p-4"><p className="text-xs text-muted">Add this secret to your authenticator app:</p><code className="mt-2 block break-all text-sm text-white">{secret}</code><p className="mt-3 break-all text-[11px] text-muted">{uri}</p><form onSubmit={enable} className="mt-4 flex gap-2"><input name="code" required pattern="[0-9]{6}" maxLength={6} inputMode="numeric" placeholder="6-digit code" className="w-44 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-sm" /><button disabled={pending} className="rounded-lg bg-accent px-3 py-2 text-sm font-semibold">Verify and enable</button></form></div>}{codes && <div className="mt-5 rounded-xl border border-amber-400/20 bg-amber-400/8 p-4"><strong className="text-sm text-amber-200">Save these one-time recovery codes now</strong><div className="mt-3 grid grid-cols-2 gap-2 font-mono text-sm">{codes.map((code) => <code key={code}>{code}</code>)}</div><button onClick={() => signOut({ callbackUrl: "/login?callbackUrl=/admin" })} className="mt-4 rounded-lg bg-white px-3 py-2 text-sm font-semibold text-black">I saved them — sign in again</button></div>}</section>;
}
