import Link from "next/link";
import { DynamicAdminForm } from "@/components/admin/dynamic-form";
import { AdminCard, AdminPageHeader, EmptyState, Pagination, StatusPill, tableClass, tdClass, thClass } from "@/components/admin/ui";
import { requireAdmin } from "@/lib/admin/authz";
import { hasPermission } from "@/lib/admin/permissions";
import { listFinance, type PageInput } from "@/lib/admin/queries";
import { formatCurrency, formatDate } from "@/lib/utils";

export default async function InvoicesPage({ searchParams }: { searchParams: Promise<PageInput> }) {
  const actor = await requireAdmin("invoices.read"); const data = await listFinance("invoices", await searchParams); if (data.type !== "invoices") throw new Error("Unexpected finance query result"); const canWrite = hasPermission(actor.role, "invoices.write");
  return <><AdminPageHeader title="Invoices" description="Invoice status and balances reconciled against the finance ledger." />
    {canWrite && <div className="mb-6"><DynamicAdminForm command="invoice.create" title="Create invoice" submitLabel="Create invoice" fields={[{ name: "bookingId", label: "Booking ID", type: "number", valueType: "number", required: true }, { name: "amount", label: "Amount (QAR)", type: "number", valueType: "number", step: "0.01", required: true }, { name: "dueDate", label: "Due date", type: "date" }, { name: "notes", label: "Notes", type: "textarea" }]} /></div>}
    <AdminCard className="overflow-hidden">{data.rows.length === 0 ? <EmptyState title="No invoices" /> : <div className="overflow-x-auto"><table className={tableClass}><thead><tr><th className={thClass}>Invoice</th><th className={thClass}>Booking / customer</th><th className={thClass}>Amount</th><th className={thClass}>Booking paid</th><th className={thClass}>Status</th><th className={thClass}>Due</th><th className={thClass}></th></tr></thead><tbody>{data.rows.map(({ invoice, bookingNumber, customerName, amountPaid }) => <tr key={invoice.id}><td className={tdClass}><strong>{invoice.invoiceNumber}</strong><div className="text-xs text-muted">Issued {formatDate(invoice.issuedAt)}</div></td><td className={tdClass}><Link href={`/admin/bookings/${invoice.bookingId}`} className="font-medium text-accent">{bookingNumber}</Link><div className="text-xs text-muted">{customerName || "—"}</div></td><td className={tdClass}>{formatCurrency(invoice.amount)}</td><td className={tdClass}>{formatCurrency(amountPaid)}</td><td className={tdClass}><StatusPill value={invoice.status} /></td><td className={tdClass}>{formatDate(invoice.dueDate)}</td><td className={tdClass}>{canWrite && <DynamicAdminForm command="invoice.update" fixed={{ id: invoice.id }} title="Edit invoice" submitLabel="Save invoice" confirmMessage="Update this invoice amount or due date?" fields={[{ name: "amount", label: "Amount", type: "number", valueType: "number", step: "0.01", required: true, defaultValue: Number(invoice.amount) }, { name: "dueDate", label: "Due date", type: "date", defaultValue: invoice.dueDate }, { name: "notes", label: "Notes", type: "textarea", defaultValue: invoice.notes }]} />}</td></tr>)}</tbody></table></div>}<Pagination page={data.page} pageSize={data.pageSize} total={data.total} pathname="/admin/invoices" /></AdminCard>
  </>;
}
