import Link from "next/link";
import { AdminCard, AdminPageHeader, MetricCard, StatusPill, tableClass, tdClass, thClass } from "@/components/admin/ui";
import { getAdminDashboard, type PageInput } from "@/lib/admin/queries";
import { formatCurrency, formatDate } from "@/lib/utils";

export default async function AdminDashboard({ searchParams }: { searchParams: Promise<PageInput> }) {
  const data = await getAdminDashboard(await searchParams);
  const metrics = data.metrics;
  const pendingPayments = Number(metrics.outstanding) > 0 ? "Needs attention" : "Clear";
  return <>
    <AdminPageHeader title="Operations dashboard" description="Commercial, finance and fleet activity in Qatar time. Revenue is separated into booked and received amounts." actions={<form className="flex gap-2"><input name="from" type="date" defaultValue={data.fromDate} className="rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-xs" /><input name="to" type="date" defaultValue={data.toDate} className="rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-xs" /><button className="rounded-lg bg-white px-3 py-2 text-xs font-semibold text-black">Apply</button></form>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Total bookings" value={String(metrics.total_bookings)} /><MetricCard label="Upcoming" value={String(metrics.upcoming_bookings)} tone="blue" /><MetricCard label="Pending" value={String(metrics.pending_bookings)} tone="amber" /><MetricCard label="Confirmed" value={String(metrics.confirmed_bookings)} tone="green" /><MetricCard label="Completed" value={String(metrics.completed_bookings)} tone="green" /></div>
    <div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Booked revenue" value={formatCurrency(metrics.booked_revenue)} /><MetricCard label="Received revenue" value={formatCurrency(data.receivedRevenue)} tone="green" /><MetricCard label="Outstanding" value={formatCurrency(metrics.outstanding)} note={pendingPayments} tone="amber" /><MetricCard label="Pending payments" value={pendingPayments} tone={pendingPayments === "Clear" ? "green" : "red"} /></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1.25fr_.75fr]">
      <AdminCard className="overflow-hidden"><div className="flex items-center justify-between px-5 py-4"><h2 className="font-semibold">Upcoming installations & dismantling</h2><Link href="/admin/bookings" className="text-xs text-accent">View bookings</Link></div><div className="overflow-x-auto"><table className={tableClass}><thead><tr><th className={thClass}>Booking</th><th className={thClass}>Installation</th><th className={thClass}>Dismantling</th><th className={thClass}>Status</th></tr></thead><tbody>{data.upcomingJobs.map((job) => <tr key={job.id}><td className={tdClass}><Link href={`/admin/bookings/${job.id}`} className="font-medium hover:text-accent">{job.eventName || job.bookingNumber}</Link><div className="text-xs text-muted">{job.bookingNumber}</div></td><td className={tdClass}>{formatDate(job.installationDate)}</td><td className={tdClass}>{formatDate(job.dismantlingDate)}</td><td className={tdClass}><StatusPill value={job.status} /></td></tr>)}</tbody></table></div></AdminCard>
      <AdminCard className="p-5"><h2 className="font-semibold">Recent administrative activity</h2><div className="mt-4 space-y-4">{data.activity.map((item) => <div key={item.id} className="border-l border-accent/30 pl-3"><p className="text-sm font-medium">{item.action.replaceAll("_", " ")}</p><p className="mt-0.5 text-xs text-muted">{item.entityType} {item.entityId ? `#${item.entityId}` : ""} · {new Intl.DateTimeFormat("en-QA", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Qatar" }).format(item.occurredAt)}</p></div>)}</div></AdminCard>
    </div>
    <AdminCard className="mt-6 p-5"><h2 className="font-semibold">Product utilization</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{data.utilization.map((row) => { const item = row as { id: number; name: string; total_cabinets: number; reserved_cabinet_days: number }; const days = Math.max(1, Math.round((Date.parse(`${data.toDate}T00:00:00Z`) - Date.parse(`${data.fromDate}T00:00:00Z`)) / 86400000) + 1); const pct = item.total_cabinets ? Math.min(100, (item.reserved_cabinet_days / (item.total_cabinets * days)) * 100) : 0; return <div key={item.id}><div className="flex justify-between text-xs"><span>{item.name}</span><span className="text-muted">{pct.toFixed(1)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/6"><div className="h-full rounded-full bg-accent" style={{ width: `${pct}%` }} /></div></div>; })}</div></AdminCard>
  </>;
}
