import { AdminCard, AdminPageHeader, EmptyState, Pagination, tableClass, tdClass, thClass } from "@/components/admin/ui";
import { listAudit, type PageInput } from "@/lib/admin/queries";

export default async function AuditLogPage({ searchParams }: { searchParams: Promise<PageInput> }) {
  const data = await listAudit(await searchParams);
  return <><AdminPageHeader title="Audit log" description="Append-only record of privileged changes. Secrets, passwords, tokens and signed URLs are excluded." actions={<form className="flex gap-2"><input name="q" defaultValue={data.q} placeholder="Action, entity or ID" className="rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm" /><button className="rounded-lg bg-white px-3 py-2 text-sm font-semibold text-black">Search</button></form>} />
    <AdminCard className="overflow-hidden">{data.rows.length === 0 ? <EmptyState title="No audit records" /> : <div className="overflow-x-auto"><table className={tableClass}><thead><tr><th className={thClass}>Time (Qatar)</th><th className={thClass}>Actor</th><th className={thClass}>Action</th><th className={thClass}>Entity</th><th className={thClass}>Change</th></tr></thead><tbody>{data.rows.map(({ log, actorName, actorEmail }) => <tr key={log.id}><td className={tdClass}>{new Intl.DateTimeFormat("en-QA", { dateStyle: "medium", timeStyle: "medium", timeZone: "Asia/Qatar" }).format(log.occurredAt)}</td><td className={tdClass}>{actorName || "System"}<div className="text-xs text-muted">{actorEmail || "—"}</div></td><td className={tdClass}><strong>{log.action}</strong></td><td className={tdClass}>{log.entityType}<div className="text-xs text-muted">{log.entityId || "—"}</div></td><td className={tdClass}><details><summary className="cursor-pointer text-xs text-accent">Inspect</summary><pre className="mt-2 max-h-64 max-w-xl overflow-auto whitespace-pre-wrap rounded-lg bg-black/30 p-3 text-[11px] text-muted">{JSON.stringify({ before: log.beforeValue, after: log.afterValue, metadata: log.metadata }, null, 2)}</pre></details></td></tr>)}</tbody></table></div>}<Pagination page={data.page} pageSize={data.pageSize} total={data.total} pathname="/admin/audit-log" query={{ q: data.q }} /></AdminCard>
  </>;
}
