import Link from "next/link";
import { AdminCard, AdminPageHeader, EmptyState, Pagination, StatusPill, tableClass, tdClass, thClass } from "@/components/admin/ui";
import { listBookings, type PageInput } from "@/lib/admin/queries";
import { BOOKING_STATUSES } from "@/lib/booking/status-transitions";
import { formatCurrency, formatDate } from "@/lib/utils";

export default async function BookingsPage({ searchParams }: { searchParams: Promise<PageInput> }) {
  const data = await listBookings(await searchParams);
  return <>
    <AdminPageHeader title="Bookings" description="Search events, monitor controlled fulfillment stages, payment position, and assigned work." actions={<form className="grid grid-cols-2 gap-2 md:flex"><input name="q" defaultValue={data.q} placeholder="Booking, event, customer" className="col-span-2 rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm" /><select name="status" defaultValue={data.status} className="rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm"><option value="">All statuses</option>{BOOKING_STATUSES.map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select><input name="from" type="date" defaultValue={data.from} className="rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm" /><input name="to" type="date" defaultValue={data.to} className="rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm" /><button className="rounded-lg bg-white px-3 py-2 text-sm font-semibold text-black">Filter</button></form>} />
    <AdminCard className="overflow-hidden">{data.rows.length === 0 ? <EmptyState title="No bookings match these filters" /> : <div className="overflow-x-auto"><table className={tableClass}><thead><tr><th className={thClass}>Booking</th><th className={thClass}>Customer</th><th className={thClass}>Event</th><th className={thClass}>Product</th><th className={thClass}>Total / outstanding</th><th className={thClass}>Status</th><th className={thClass}></th></tr></thead><tbody>{data.rows.map((row) => <tr key={row.id}><td className={tdClass}><strong>{row.bookingNumber}</strong><div className="mt-1 text-xs text-muted">{formatDate(row.installationDate)} → {formatDate(row.dismantlingDate)}</div></td><td className={tdClass}>{row.customerName || "—"}</td><td className={tdClass}>{row.eventName}<div className="mt-1 text-xs text-muted">{formatDate(row.eventDate)}</div></td><td className={tdClass}>{row.productName || "Historical product"}</td><td className={tdClass}>{formatCurrency(row.total)}<div className="mt-1 text-xs text-muted">Due {formatCurrency(Math.max(0, Number(row.total) - Number(row.amountPaid)))}</div></td><td className={tdClass}><StatusPill value={row.status} /><div className="mt-2"><StatusPill value={row.paymentStatus} /></div></td><td className={tdClass}><Link href={`/admin/bookings/${row.id}`} className="text-xs font-semibold text-accent">Open</Link></td></tr>)}</tbody></table></div>}<Pagination page={data.page} pageSize={data.pageSize} total={data.total} pathname="/admin/bookings" query={{ q: data.q, status: data.status, from: data.from, to: data.to }} /></AdminCard>
  </>;
}
