import { AdminCommandButton, DynamicAdminForm, type AdminField } from "@/components/admin/dynamic-form";
import { AdminCard, AdminPageHeader, StatusPill } from "@/components/admin/ui";
import Link from "next/link";
import { requireAdmin } from "@/lib/admin/authz";
import { hasPermission } from "@/lib/admin/permissions";
import { getContentAdminData } from "@/lib/admin/queries";
import { PAGE_SECTION_DEFINITIONS } from "@/lib/cms/schemas";
import { formatDate } from "@/lib/utils";

const SECTION_DEFAULTS: Record<string, Record<string, unknown>> = {
  "home.hero": { eyebrow: "Premium LED screen rental in Qatar", title: "Make every event", highlight: "impossible to ignore.", description: "High-resolution LED displays with professional delivery, installation and support.", primaryLabel: "Configure your screen", primaryHref: "/configure", secondaryLabel: "View projects", secondaryHref: "/projects" },
  "home.about": { heading: "LED display experiences, delivered professionally", body: "LEDWAVE provides premium modular LED screens for events, exhibitions and productions across Qatar." },
  "home.services": { heading: "Complete event display services", intro: "From planning through dismantling, our team supports your event.", items: [{ title: "LED screen rental", description: "Flexible indoor and outdoor screen configurations." }, { title: "Installation", description: "Professional installation and testing." }] },
  "home.why_choose_us": { heading: "Why choose LEDWAVE", intro: "Reliable equipment and an experienced local team.", items: [{ title: "Professional support", description: "Technical support from preparation to dismantling." }, { title: "Transparent pricing", description: "Clear, configurable quotations." }] },
  "home.cta": { heading: "Ready to plan your screen?", body: "Build a configuration and request your quotation online.", buttonLabel: "Start configuring", buttonHref: "/configure" },
  "about.intro": { heading: "About LEDWAVE", body: "We deliver high-quality LED display solutions for events across Qatar." },
};

const recordFields: Record<string, AdminField[]> = {
  faq: [{ name: "question", label: "Question", required: true }, { name: "answer", label: "Answer", type: "textarea", required: true }, { name: "sortOrder", label: "Order", type: "number", valueType: "number", required: true }, { name: "isActive", label: "Visible", type: "checkbox", valueType: "boolean" }],
  testimonial: [{ name: "name", label: "Customer name", required: true }, { name: "company", label: "Company" }, { name: "quote", label: "Quote", type: "textarea", required: true }, { name: "rating", label: "Rating", type: "number", valueType: "number", required: true }, { name: "sortOrder", label: "Order", type: "number", valueType: "number", required: true }, { name: "isActive", label: "Visible", type: "checkbox", valueType: "boolean" }],
  project: [{ name: "title", label: "Project title", required: true }, { name: "category", label: "Category", required: true }, { name: "description", label: "Description", type: "textarea" }, { name: "imageUrl", label: "Image URL (or media endpoint)", required: true }, { name: "mediaAssetId", label: "Public media asset ID", type: "number", valueType: "nullableNumber" }, { name: "eventDate", label: "Event date", type: "date" }, { name: "sortOrder", label: "Order", type: "number", valueType: "number", required: true }, { name: "isActive", label: "Visible", type: "checkbox", valueType: "boolean" }],
  stat: [{ name: "label", label: "Label", required: true }, { name: "value", label: "Value", required: true }, { name: "suffix", label: "Suffix" }, { name: "sortOrder", label: "Order", type: "number", valueType: "number", required: true }, { name: "isActive", label: "Visible", type: "checkbox", valueType: "boolean" }],
};

export default async function ContentPage() {
  const actor = await requireAdmin("content.read"); const data = await getContentAdminData(); const canWrite = hasPermission(actor.role, "content.write"); const canPublish = hasPermission(actor.role, "content.publish");
  const byKey = new Map(data.sections.map((section) => [`${section.page}.${section.sectionKey}`, section]));
  return <><AdminPageHeader title="Website content" description="Structured, validated content fields only. Page components, layout and executable code remain outside the CMS." actions={<Link href="/admin/content/preview?page=home" className="rounded-lg border border-white/10 px-3 py-2 text-sm font-semibold hover:bg-white/5">Preview drafts</Link>} />
    <div className="space-y-6"><AdminCard className="p-5"><h2 className="font-display text-lg font-semibold">Structured page sections</h2><p className="mt-1 text-sm text-muted">Save a draft for review or publish immediately if your role permits it.</p><div className="mt-5 space-y-4">{Object.entries(PAGE_SECTION_DEFINITIONS).map(([key, definition]) => { const [page, ...rest] = key.split("."); const sectionKey = rest.join("."); const current = byKey.get(key); return <div key={key} className="rounded-xl border border-white/8"><div className="flex items-center justify-between px-4 py-3"><div><strong className="text-sm">{definition.label}</strong><p className="text-xs text-muted">{key} · version {current?.version ?? 0}{current?.updatedAt ? ` · ${formatDate(current.updatedAt)}` : ""}</p></div><StatusPill value={current?.status ?? "not created"} /></div>{canWrite && <DynamicAdminForm command="content.section_save" fixed={{ page, sectionKey, locale: current?.locale ?? "en" }} compact submitLabel={canPublish ? "Save / publish" : "Save draft"} fields={[{ name: "content", label: "Validated section data", type: "json", valueType: "json", required: true, defaultValue: current?.content as Record<string, unknown> || SECTION_DEFAULTS[key] }, { name: "sortOrder", label: "Display order", type: "number", valueType: "number", required: true, defaultValue: current?.sortOrder ?? 0 }, { name: "isVisible", label: "Visible", type: "checkbox", valueType: "boolean", defaultValue: current?.isVisible ?? true }, { name: "publish", label: canPublish ? "Publish now" : "Publishing requires super_admin", type: "checkbox", valueType: "boolean", defaultValue: false }]} />}</div>; })}</div></AdminCard>
      {(["faq", "testimonial", "project", "stat"] as const).map((entity) => { const rows = entity === "faq" ? data.faqs : entity === "testimonial" ? data.testimonials : entity === "project" ? data.projects : data.stats; return <AdminCard key={entity} className="p-5"><h2 className="font-display text-lg font-semibold capitalize">{entity === "stat" ? "Site statistics" : `${entity}s`}</h2>{canWrite && <div className="mt-4"><DynamicAdminForm command="content.record_save" fixed={{ entity }} nesting="data" title={`Add ${entity}`} submitLabel={`Add ${entity}`} fields={recordFields[entity].map((field) => ({ ...field, defaultValue: field.name === "sortOrder" ? rows.length : field.name === "rating" ? 5 : field.name === "isActive" ? true : field.defaultValue }))} /></div>}<div className="mt-4 space-y-3">{rows.map((record) => { const values = record as unknown as Record<string, unknown>; return <details key={record.id} className="rounded-xl border border-white/8"><summary className="flex cursor-pointer list-none items-center justify-between p-4"><span className="font-medium">{String(values.question || values.name || values.title || values.label || `#${record.id}`)}</span><StatusPill value={record.isActive ? "active" : "inactive"} /></summary>{canWrite && <div className="border-t border-white/8"><DynamicAdminForm command="content.record_save" fixed={{ entity, id: record.id }} nesting="data" compact submitLabel="Save record" fields={recordFields[entity].map((field) => ({ ...field, defaultValue: values[field.name] as string | number | boolean | null }))} /><div className="px-5 pb-5"><AdminCommandButton payload={{ action: "content.record_archive", entity, id: record.id }} tone="danger" confirmMessage="Archive this content item?">Archive</AdminCommandButton></div></div>}</details>; })}</div></AdminCard>; })}
      <AdminCard className="p-5"><h2 className="font-display text-lg font-semibold">Revision history</h2><div className="mt-4 space-y-3">{data.revisions.length ? data.revisions.map((revision) => <details key={revision.id} className="rounded-xl border border-white/8 p-4"><summary className="cursor-pointer text-sm font-medium">{revision.entityType} #{revision.entityId} · version {revision.version} · {formatDate(revision.createdAt)}</summary><pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap rounded-lg bg-black/30 p-3 text-xs text-muted">{JSON.stringify(revision.content, null, 2)}</pre></details>) : <p className="text-sm text-muted">Revisions appear after the first edit to a saved page section.</p>}</div></AdminCard>
    </div>
  </>;
}
