import Link from "next/link";
import { DynamicAdminForm } from "@/components/admin/dynamic-form";
import { AdminCard, AdminPageHeader, EmptyState, Pagination, StatusPill, tableClass, tdClass, thClass } from "@/components/admin/ui";
import { requireAdmin } from "@/lib/admin/authz";
import { hasPermission } from "@/lib/admin/permissions";
import { listFinance, type PageInput } from "@/lib/admin/queries";
import { formatCurrency, formatDate } from "@/lib/utils";

export default async function PaymentsPage({ searchParams }: { searchParams: Promise<PageInput> }) {
  const actor = await requireAdmin("payments.read"); const data = await listFinance("payments", await searchParams); if (data.type !== "payments") throw new Error("Unexpected finance query result"); const canRecord = hasPermission(actor.role, "payments.record");
  return <><AdminPageHeader title="Payments" description="Append-only payment ledger. Corrections use linked refunds or reversals; booking and invoice balances reconcile transactionally." />
    {canRecord && <div className="mb-6"><DynamicAdminForm command="payment.record" title="Record a received payment" submitLabel="Record payment" confirmMessage="Confirm this payment record?" fields={[{ name: "bookingId", label: "Booking ID", type: "number", valueType: "number", required: true }, { name: "invoiceId", label: "Invoice ID (optional)", type: "number", valueType: "nullableNumber" }, { name: "amount", label: "Amount (QAR)", type: "number", valueType: "number", step: "0.01", required: true }, { name: "method", label: "Method", type: "select", required: true, options: [{ value: "bank_transfer", label: "Bank transfer" }, { value: "card", label: "Card" }, { value: "cash", label: "Cash" }, { value: "other", label: "Other" }] }, { name: "reference", label: "Reference" }, { name: "paidAt", label: "Paid at (UTC/local offset)", type: "datetime-local" }, { name: "notes", label: "Internal notes", type: "textarea" }]} /></div>}
    <AdminCard className="overflow-hidden">{data.rows.length === 0 ? <EmptyState title="No payment records" /> : <div className="overflow-x-auto"><table className={tableClass}><thead><tr><th className={thClass}>Payment</th><th className={thClass}>Booking / customer</th><th className={thClass}>Amount</th><th className={thClass}>Method</th><th className={thClass}>Status</th><th className={thClass}>Recorded</th><th className={thClass}></th></tr></thead><tbody>{data.rows.map(({ payment, bookingNumber, customerName }) => <tr key={payment.id}><td className={tdClass}>#{payment.id}<div className="text-xs text-muted">{payment.reference || payment.kind}</div></td><td className={tdClass}><Link href={`/admin/bookings/${payment.bookingId}`} className="font-medium text-accent">{bookingNumber}</Link><div className="text-xs text-muted">{customerName || "—"}</div></td><td className={tdClass}>{formatCurrency(payment.amount)}</td><td className={tdClass}>{payment.method}</td><td className={tdClass}><StatusPill value={payment.status} /></td><td className={tdClass}>{formatDate(payment.recordedAtUtc || payment.paidAt)}</td><td className={tdClass}>{canRecord && payment.kind === "payment" && payment.status === "completed" ? <DynamicAdminForm command="payment.refund" fixed={{ paymentId: payment.id }} title="Refund / reverse" submitLabel="Create refund" confirmMessage="Create this linked refund?" fields={[{ name: "amount", label: "Refund amount", type: "number", valueType: "number", step: "0.01", required: true, defaultValue: Number(payment.amount) }, { name: "notes", label: "Reason", type: "textarea", required: true }]} /> : null}</td></tr>)}</tbody></table></div>}<Pagination page={data.page} pageSize={data.pageSize} total={data.total} pathname="/admin/payments" /></AdminCard>
  </>;
}
